### ISSUE TITLE
crashed with angular 8

### ISSUE THREAD

**Issue by Diluka** [huan/rx-queue#57]
```log
ERROR TypeError: Class constructor Subject cannot be invoked without 'new'
    at new RxQueue (rx-queue.umd.js:59)
```

using latest version

**Comment by huan** [comment]
Thanks for reporting this problem.

Cloud you please provide a minimum reproducible code to me so that I could fix that based on your code?

**Comment by huan** [comment]
I hope your problem has been solved, cheers!

**Comment by tyanders1987** [comment]
Hello, I am having the same issue.  I am using Angular 9 with ES2015.  If I change to ES5, there are no issues.  I'd prefer not to have to change my target from ES2015 to ES5.  Is there any other work around?
