### ISSUE TITLE
Is there away to clear the queue?

### ISSUE THREAD

**Issue by zhex900** [huan/rx-queue#74]
Hi,

Is there a way to clear the queue? 

For example, I have a delay queue. Say runs every 1 minute. The queue has 100 items. 

At some point, I want to clear the queue. Is this possible? 

I don't want to end the the queue.  So I don't want to us `complete`. 

What should I do. 

Also is it possible to get the queue size?

**Comment by huan** [comment]
It's doable.

According to the following code:

https://github.com/huan/rx-queue/blob/908830bfdeb90c9e315ec849691fd038293cef10/src/delay-queue.ts#L28-L46

We can add a new method named `clear()` and do the follow jobs:

```ts
     this.subscription.unsubscript()

     this.subject      = new Subject<T>() 
     this.subscription = this.subject.pipe( 
       concatMap(x => concat( 
         of(x),                    // emit first item right away 
         /** 
          * Issue #71 - DelayQueue failed: behavior breaking change after RxJS from v6 to v7 
          *  https://github.com/huan/rx-queue/issues/71 
          */ 
         timer(this.period).pipe( 
           ignoreElements(), 
         ), 
       )), 
     ).subscribe((item: T) => super.next(item)) 
```

Which means:

1. we unsubscribe from the old subject
2. we create a new subject (drop the old one)
3. we subscribe to the new subject (which is empty)

**Comment by zhex900** [comment]
Thank you! Do you plan to add that to the next release?

**Comment by huan** [comment]
If you can submit a pull request, I'd very glad to accept it.

**Comment by zhex900** [comment]
please have a look at my PR
 https://github.com/huan/rx-queue/pull/75
